// <auto-generated />
using Cidades.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cidades.Persistencia.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210626230007_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Cidades.Dominio.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroHabitantes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Cidades.Dominio.Fronteira", b =>
                {
                    b.Property<int>("CidadeOrigemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeFronteiraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CidadeOrigemId", "CidadeFronteiraId");

                    b.HasIndex("CidadeFronteiraId");

                    b.ToTable("Fronteiras");
                });

            modelBuilder.Entity("Cidades.Dominio.Fronteira", b =>
                {
                    b.HasOne("Cidades.Dominio.Cidade", "CidadeFronteira")
                        .WithMany("Fronteiras")
                        .HasForeignKey("CidadeFronteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cidades.Dominio.Cidade", "CidadeOrigem")
                        .WithMany("Origens")
                        .HasForeignKey("CidadeOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CidadeFronteira");

                    b.Navigation("CidadeOrigem");
                });

            modelBuilder.Entity("Cidades.Dominio.Cidade", b =>
                {
                    b.Navigation("Fronteiras");

                    b.Navigation("Origens");
                });
#pragma warning restore 612, 618
        }
    }
}
